version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: audio-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:

  spring-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/audio-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: